RhumbLine : remove unused private member field
to fix this warning :

Rhumb.hpp:469:10: error: private field '_exact' is not used [-Werror,-Wunused-private-field]
    bool _exact;